export const Sample = [
  {
    emp_name: 'Ram',
    emp_id: '20001',
    emp_address: 'D.No 11/1, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Mobile Development',
    emp_designation: 'Team Lead',
    emp_experience: 'Have 5 years of experience in React Native',
    emp_salary: '10,00,000',
    emp_photo_path: require('../Assets/images/jef.jpg'),
    emp_Timeline_path: require('../Assets/images/JefTL.jpg'),
    latitude: 17.346064,
    longitude: 78.448519,
  },
  {
    emp_name: 'Raj',
    emp_id: '20002',
    emp_address: 'D.No 11/2, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Mobile Development',
    emp_designation: 'Developer',
    emp_experience: 'Have 1 years of experience in React Native',
    emp_salary: '2,00,000',
    emp_photo_path: require('../Assets/images/elon.jpg'),
    emp_Timeline_path: require('../Assets/images/elonTL.jpg'),
    latitude: 17.362455,
    longitude: 78.429319,
  },
  {
    emp_name: 'Kumar',
    emp_id: '20003',
    emp_address: 'D.No 11/3, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Mobile Development',
    emp_designation: 'Developer',
    emp_experience: 'Have 2 years of experience in React Native',
    emp_salary: '5,00,000',
    emp_photo_path: require('../Assets/images/MZ.jpeg'),
    emp_Timeline_path: require('../Assets/images/MZTL.jpg'),
    latitude: 17.389991,
    longitude: 78.383301,
  },
  {
    emp_name: 'Suresh',
    emp_id: '20004',
    emp_address: 'D.No 11/4, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Tester',
    emp_designation: 'Team Lead',
    emp_experience: 'Have 5 years of experience in React Native',
    emp_salary: '10,00,000',
    emp_photo_path: require('../Assets/images/jef.jpg'),
    emp_Timeline_path: require('../Assets/images/JefTL.jpg'),
    latitude: 17.481034,
    longitude: 78.412899,
  },
  {
    emp_name: 'Reddy',
    emp_id: '20005',
    emp_address: 'D.No 11/1, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Tester',
    emp_designation: 'Tester',
    emp_experience: 'Have 1 years of experience in React Native',
    emp_salary: '2,00,000',
    emp_photo_path: require('../Assets/images/elon.jpg'),
    emp_Timeline_path: require('../Assets/images/elonTL.jpg'),
    latitude: 17.423962,
    longitude: 78.486352,
  },
  {
    emp_name: 'Akash',
    emp_id: '20006',
    emp_address: 'D.No 11/6, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Web Development',
    emp_designation: 'Team Lead',
    emp_experience: 'Have 5 years of experience in React Native',
    emp_salary: '10,00,000',
    emp_photo_path: require('../Assets/images/MZ.jpeg'),
    emp_Timeline_path: require('../Assets/images/MZTL.jpg'),
    latitude: 17.438478,
    longitude: 78.362724,
  },
  {
    emp_name: 'Naresh',
    emp_id: '20007',
    emp_address: 'D.No 11/7, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Web Development',
    emp_designation: 'Developer',
    emp_experience: 'Have 1 years of experience in React Native',
    emp_salary: '2,00,000',
    emp_photo_path: require('../Assets/images/jef.jpg'),
    emp_Timeline_path: require('../Assets/images/JefTL.jpg'),
    latitude: 17.399831,
    longitude: 78.350343,
  },
  {
    emp_name: 'Raju',
    emp_id: '20008',
    emp_address: 'D.No 11/8, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Backend',
    emp_designation: 'Team Lead',
    emp_experience: 'Have 5 years of experience in React Native',
    emp_salary: '10,00,000',
    emp_photo_path: require('../Assets/images/elon.jpg'),
    emp_Timeline_path: require('../Assets/images/elonTL.jpg'),
    latitude: 17.408989,
    longitude: 78.375754,
  },
  {
    emp_name: 'Rakesh',
    emp_id: '20009',
    emp_address: 'D.No 11/9, Joy School Road,Madhura Nagar, hyderabad',
    emp_department: 'Backend',
    emp_designation: 'Developer',
    emp_experience: 'Have 1 years of experience in React Native',
    emp_salary: '2,00,000',
    emp_photo_path: require('../Assets/images/MZ.jpeg'),
    emp_Timeline_path: require('../Assets/images/MZTL.jpg'),
    latitude: 17.325023,
    longitude: 78.4780001,
  },
];
